spring:
  kafka:
    bootstrap-servers: 192.168.0.128:9092
    producer:
      retries: 3
      batch-size: 1000
      buffer-memory: 33554432
    consumer:
      group-id: test
      auto-offset-reset: earliest
      max-poll-records: 3000
      enable-auto-commit: false
      auto-commit-interval: 1000 #自动提交时间间隔，单位ms
      batch:
        concurrency: 3  # 批消费并发量，小于或等于Topic的分区数
