log:
#  home: /Users/hongyan/IdeaProjects/MyProject/hzbb-fighting/demo/demo_logs

#设置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
#        password: root
        password: Dsj(AEN(춇춄춄춉))
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        url: jdbc:mysql://47.95.36.245:3306/test2?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: temp
        password: databpsPass4you!
        driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 15
      min-idle: 15
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: ""
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      connection-properties: false

syslog:
  producer:
    host: 127.0.0.1
    port: 5144
    protocol: UDP

  consumer:
    host: 127.0.0.1
    port: 5144
    protocol: UDP

idaas:
  decerypt:
    decryptPassword: 123456789 # 最低配置,必须
    url: wwww.baidu.com  #starter去远程获取密钥的地址(根据实际配置,若没有去远程获取可不配),非必须
    customGetCryptorClass: com.athaite.idaas.CustomGetCryptor  #客户端自己代码去远程获取密钥的类(此类要实现我们starter的接口CustomGetCryptorService),非必须
