spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Dsj(AEN(Vcxko6LyrTY76RswDbYb0Q==))
    url: jdbc:mysql://localhost:3306/demo?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  name: Dsj(AEN(ayiqS3MWnwHRMv4Ckc85yA==))

#idaas:
#  decerypt:
#    decryptPassword: 12345678 # 最低配置,必须
#    url: wwww.baidu.com  #starter去远程获取密钥的地址(根据实际配置,若没有去远程获取可不配),非必须
#    customGetCryptorClass: com.athaite.idaas.CustomGetCryptor  #客户端自己代码去远程获取密钥的类(此类要实现我们starter的接口CustomGetCryptorService),非必须
