spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: temp
    password: databpsPass4you!
    url: jdbc:mysql://47.95.36.245:3306/mybatis_plus_test?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true